### ISSUE TITLE
where to set openai key, and how to swap in elevenlabs?

### ISSUE THREAD

**Issue by relaxwithadam** [acmeyer/phone_call_bot#1]
so excited to try this, sorry for the stupid questions

**Comment by acmeyer** [comment]
You can just create a new `.env` file within the directory and add them there, for example:

```
OPENAI_API_KEY=sk-1234
ELEVEN_LABS_API_KEY=1234
ELEVEN_LABS_VOICE_ID=1234
```

Just an FYI, the code no longer uses Eleven Labs and uses OpenAI's text to speech instead but you can update the `text_to_speech` function in the `main.py` file to something like [this](https://github.com/acmeyer/phone_call_bot/commit/31f7c5255069236b55d7c15db3defe464c639f68#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L67) if you wanted to add it back.
